### ISSUE TITLE
Changing Play/Pause Button

### ISSUE THREAD

**Issue by GauravCreed** [Cleveroad/MusicBobber#10]
Hi @Iojjj 

i have little issue on changing the play/pause button on when my app onPause(), what i need.? i want to change the play/pause button on depending on whether the music is play or pause on when my app is going on a onPause(), i just show audioWidget onPause() like `@Override
    protected void onPause() {
        super.onPause();
        audioWidget.show(100, 100);
    }` and i maintain **audioWidget.controller()** click separately. 

so how can i change play/pause icon as per my requirement.

also when i call audioWidget.hide() in onResume() of activity it will crash app and my crash log like       `Process: com.example.gaurav.myapplication, PID: 23850
    java.lang.IllegalArgumentException: View=com.cleveroad.audiowidget.PlayPauseButton{27b58e94 V.ED.... ......I. 0,0-240,240} not attached to window manager
            at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:421)
            at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:305)
            at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:74)
            at com.cleveroad.audiowidget.AudioWidget.updatePlayPauseButtonPosition(AudioWidget.java:421)
            at com.cleveroad.audiowidget.AudioWidget.access$6500(AudioWidget.java:31)
            at com.cleveroad.audiowidget.AudioWidget$ExpandCollapseWidgetCallback.onMoved(AudioWidget.java:653)
            at com.cleveroad.audiowidget.TouchManager$StickyEdgeAnimator.lambda$new$1(TouchManager.java:389)
            at com.cleveroad.audiowidget.TouchManager$StickyEdgeAnimator.access$lambda$0(TouchManager.java)
            at com.cleveroad.audiowidget.TouchManager$StickyEdgeAnimator$$Lambda$1.onAnimationUpdate(Unknown Source)
            at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1283)
            at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1207)
            at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1248)
            at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:659)
            at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:682)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
            at android.view.Choreographer.doCallbacks(Choreographer.java:603)
            at android.view.Choreographer.doFrame(Choreographer.java:571)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
            at android.os.Handler.handleCallback(Handler.java:815)
            at android.os.Handler.dispatchMessage(Handler.java:104)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:5576)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)`

Thanks.

**Comment by Iojjj** [comment]
We'll put this to the list of fixes for future release.

This issue happens because of sticky edge animation. When you call **hide()**, view removed from window. Animator tries to update view's position and this crash is happened.

**Comment by Iojjj** [comment]
fixed in 0.9.2. Check [migration guide](https://github.com/Cleveroad/MusicBobber#migration-from-v091-to-v092)
