### ISSUE TITLE
IllegalArgumentException when hide and show widget

### ISSUE THREAD

**Issue by jordyamc** [Cleveroad/MusicBobber#5]
![captura](https://cloud.githubusercontent.com/assets/6831873/14860028/6ae78b30-0c6c-11e6-81b9-712734971c12.JPG)

View=com.cleveroad.audiowidget.PlayPauseButton{e5daca4 V.ED..... ......I. 0,0-240,240} not attached to window manager

I get IllegalArgumentException at audiowidget.show(int,int) after hide it with audiowidget.hide()

**Comment by Iojjj** [comment]
Please post a stacktrace with line numbers so I can check where this happens.

**Comment by jordyamc** [comment]
`java.lang.IllegalStateException: View com.cleveroad.audiowidget.RemoveWidgetView{a715358 V.ED..... ......I. 0,0-120,120} has already been added to the window manager.
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:281)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
at com.cleveroad.audiowidget.AudioWidget.show(AudioWidget.java:462)
at com.cleveroad.audiowidget.AudioWidget.show(AudioWidget.java:347)
at knf.animeflv.Recyclers.AdapterDialogPref.showHideWidget(AdapterDialogPref.java:140)
at knf.animeflv.Recyclers.AdapterDialogPref.access$000(AdapterDialogPref.java:30)
at knf.animeflv.Recyclers.AdapterDialogPref$3.onClick(AdapterDialogPref.java:114)
at android.view.View.performClick(View.java:5204)
at android.view.View$PerformClick.run(View.java:21158)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by Iojjj** [comment]
Released new version v.0.9.1 with fix of this issue. It will take some time until new version will be available for downloading.
